config/routes.rb
Rails.application.routes.draw do
  resources :your_scaffolds

  resources :posts do
	resources :comments
end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
 belongs_to :post
 validates_presence_of :post_id
 validates_presence_of :body
end

app/models/post.rb
class Post < ActiveRecord::Base
 has_many :comments, dependent: :destroy
 validates_presence_of :title
 validates_presence_of :body
end

app/models/your_scaffold.rb
class YourScaffold < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
 # protect_from_forgery with: :exception
   protect_from_forgery with: :null_session
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @post, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
	format.js #create.js.erb
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
	
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:post_id, :body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate, except: [:index, :show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end

	def authenticate
	 authenticate_or_request_with_http_basic do |name, password|
	  name == "admin" && password == "secret"
	end
      end

end

app/controllers/your_scaffolds_controller.rb
class YourScaffoldsController < ApplicationController
  before_action :set_your_scaffold, only: [:show, :edit, :update, :destroy]

  # GET /your_scaffolds
  # GET /your_scaffolds.json
  def index
    @your_scaffolds = YourScaffold.all
  end

  # GET /your_scaffolds/1
  # GET /your_scaffolds/1.json
  def show
  end

  # GET /your_scaffolds/new
  def new
    @your_scaffold = YourScaffold.new
  end

  # GET /your_scaffolds/1/edit
  def edit
  end

  # POST /your_scaffolds
  # POST /your_scaffolds.json
  def create
    @your_scaffold = YourScaffold.new(your_scaffold_params)

    respond_to do |format|
      if @your_scaffold.save
        format.html { redirect_to @your_scaffold, notice: 'Your scaffold was successfully created.' }
        format.json { render :show, status: :created, location: @your_scaffold }
      else
        format.html { render :new }
        format.json { render json: @your_scaffold.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /your_scaffolds/1
  # PATCH/PUT /your_scaffolds/1.json
  def update
    respond_to do |format|
      if @your_scaffold.update(your_scaffold_params)
        format.html { redirect_to @your_scaffold, notice: 'Your scaffold was successfully updated.' }
        format.json { render :show, status: :ok, location: @your_scaffold }
      else
        format.html { render :edit }
        format.json { render json: @your_scaffold.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /your_scaffolds/1
  # DELETE /your_scaffolds/1.json
  def destroy
    @your_scaffold.destroy
    respond_to do |format|
      format.html { redirect_to your_scaffolds_url, notice: 'Your scaffold was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_your_scaffold
      @your_scaffold = YourScaffold.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def your_scaffold_params
      params.require(:your_scaffold).permit(:title, :description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/your_scaffolds_helper.rb
module YourScaffoldsHelper
end

app/views/comments/_comment.html.erb
<%= div_for comment do %>
   <p>
    <strong>Posted <%= time_ago_in_words(comment.created_at) %> ago</strong><br />
    <%= h(comment.body) %>
   </p> 
<% end %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.number_field :post_id %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/create.js.erb
var new_comment = $("<%= escape_javascript(render(:partial => @comment))%>").hide();
$('#comments').prepend(new_comment);
$('#comment_<%= @comment.id %>').fadeIn('slow');
$('#new_comment')[0].reset(); 

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.post_id %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @comment.post_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  <% @posts.reverse.each do |post|  %>
   <tr>
	<td><%= link_to post.title, post %></td>
	<td><%= time_ago_in_words(post.created_at) %> Atras</strong><br />
        <td><%= link_to 'Editar', edit_post_path(post) %></td>
        <td><%= link_to 'Destruir', post, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
      </tr>
	<tr>
	<td><%= post.body %></td>
	</tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<h2>Comments</h2>
<div id="comments">
   <%= render :partial => @post.comments.reverse %>  
</div>

<%= form_for([@post, Comment.new], remote: true) do |f| %>
  <p><%= f.label :body, "New Comment" %><br />
     <%= f.text_area :body %>
  </p>
  <p><%= f.submit "Add Comment" %></p>
<% end %>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/your_scaffolds/_form.html.erb
<%= form_for(@your_scaffold) do |f| %>
  <% if @your_scaffold.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@your_scaffold.errors.count, "error") %> prohibited this your_scaffold from being saved:</h2>

      <ul>
      <% @your_scaffold.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/your_scaffolds/edit.html.erb
<h1>Editing your_scaffold</h1>

<%= render 'form' %>

<%= link_to 'Show', @your_scaffold %> |
<%= link_to 'Back', your_scaffolds_path %>

app/views/your_scaffolds/index.html.erb
<h1>Listing your_scaffolds</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @your_scaffolds.each do |your_scaffold| %>
      <tr>
        <td><%= your_scaffold.title %></td>
        <td><%= your_scaffold.description %></td>
        <td><%= your_scaffold.image %></td>
        <td><%= link_to 'Show', your_scaffold %></td>
        <td><%= link_to 'Edit', edit_your_scaffold_path(your_scaffold) %></td>
        <td><%= link_to 'Destroy', your_scaffold, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Your scaffold', new_your_scaffold_path %>

app/views/your_scaffolds/new.html.erb
<h1>New your_scaffold</h1>

<%= render 'form' %>

<%= link_to 'Back', your_scaffolds_path %>

app/views/your_scaffolds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @your_scaffold.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @your_scaffold.description %>
</p>

<p>
  <strong>Image:</strong>
  <%= @your_scaffold.image %>
</p>

<%= link_to 'Edit', edit_your_scaffold_path(@your_scaffold) %> |
<%= link_to 'Back', your_scaffolds_path %>